### ISSUE TITLE
'gulp test' Error: Cannot find module 'jsdom'

### ISSUE THREAD

**Issue by drew-isnotnull** [connect-group/frontend-technical-test#1]
Windows10, node 7.3.0, npm 3.10.10

I'm currently working on the technical test, but "gulp test" gives the following error even after reverting to the origin master branch:
```
C:\PROJECTS\connect-technical-test>gulp test
[23:38:27] Using gulpfile C:\PROJECTS\connect-technical-test\gulpfile.js
[23:38:27] Starting 'test'...
Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references t
o remove this warning.
[23:38:28] 'test' errored after 687 ms
[23:38:28] Error: Cannot find module 'jsdom'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/PROJECTS/connect-technical-test/setupTest.js:6:15)
    at Module._compile (module.js:571:32)
    at loader (C:\PROJECTS\connect-technical-test\node_modules\babel-register\lib\n
ode.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\PROJECTS\connect
-technical-test\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

I have tried adding "jsdom" to packages.json just as a quick attempt at a fix, and that instead gives an error "jsdom is not a function".

I would normally spend more time trying to fix it or at least try to get closer to finding the cause but I am on vacation and need to get the technical test completed so will be focussing my time on the main task (without tests, eek!). If any further info is required please do ask, thanks.

Drew

**Comment by bretthadley** [comment]
@drew-isnotnull Thanks for reporting the issue. I just updated jsom so should be good now.
